<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AKSES KELAS</name>
   <tag></tag>
   <elementGuidId>b6129191-1062-43c2-ac29-d014a769b360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-wrapper']/div/div[2]/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20ec66d8-a377-4e3a-ba13-015588ed4c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bootcamp/kelas/jabar-coding-camp-batch-2-laravel/6e2f4d89-ba28-42d9-8f4c-fe7ab996feb5</value>
      <webElementGuid>65e98077-282b-44d0-b7ed-49cab5b11270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>a61fa27f-a756-4dfe-b6d8-fd36ee09fd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AKSES KELAS</value>
      <webElementGuid>b337a398-48a2-4556-8f42-2cf02ce88937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-content container-fluid&quot;]/div[@class=&quot;page-content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/div[@class=&quot;card border-bottom border-info rounded&quot;]/div[@class=&quot;card-header d-flex justify-content-between align-items-center&quot;]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>284e9598-02ed-491c-b984-b847407712fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>686e5bd5-64a3-4179-892f-8b959390b9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AKSES KELAS')]</value>
      <webElementGuid>b92e35e0-af96-4348-82ab-d24befc73c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jabar Coding Camp Batch 2 - Laravel'])[1]/following::a[1]</value>
      <webElementGuid>95e63c31-0dfa-492e-a77a-286b2521d775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat belajar dan tetap semangat!'])[1]/following::a[1]</value>
      <webElementGuid>d5b96a44-9bd4-46ba-9462-a35459c870eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch 4'])[1]/preceding::a[1]</value>
      <webElementGuid>d41b5bcd-0598-4693-8df3-fd68e0ffa56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Freelance Project Bidding Batch 2'])[1]/preceding::a[1]</value>
      <webElementGuid>8cbc3bed-1bd6-461f-b30c-eec0f51127c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AKSES KELAS']/parent::*</value>
      <webElementGuid>7ccb59c9-c3aa-468a-bd3e-910d4b919748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/bootcamp/kelas/jabar-coding-camp-batch-2-laravel/6e2f4d89-ba28-42d9-8f4c-fe7ab996feb5')]</value>
      <webElementGuid>d6d0afe0-a74e-421b-a5d6-75b922a9f2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>2543976a-b65b-48c2-aca2-b01abcf93461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/bootcamp/kelas/jabar-coding-camp-batch-2-laravel/6e2f4d89-ba28-42d9-8f4c-fe7ab996feb5' and (text() = 'AKSES KELAS' or . = 'AKSES KELAS')]</value>
      <webElementGuid>25f5afaf-95a6-492b-8f36-2a629a17d64b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
