<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JS Introduction</name>
   <tag></tag>
   <elementGuidId>d746d7db-2b1a-45bf-bd2d-ace38dfa044d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftmenuinnerinner']/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf4e812e-f3f7-4421-b893-02eab231f3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>1ae87fc7-9b8f-4231-a344-c51c649c0149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>js_intro.asp</value>
      <webElementGuid>01e3e2c9-8b3e-43f2-8f76-17e362f83a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JS Introduction</value>
      <webElementGuid>b015c622-d37e-4db6-ba74-1537b68c2c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftmenuinnerinner&quot;)/a[2]</value>
      <webElementGuid>7053256c-cb3c-4ec5-ba3d-675312c023b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftmenuinnerinner']/a[2]</value>
      <webElementGuid>9949d4aa-5252-4571-b0b9-bb046b88b379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JS Introduction')]</value>
      <webElementGuid>fba87b76-4fa0-4e10-8b72-e8ac9d41a8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS HOME'])[1]/following::a[1]</value>
      <webElementGuid>72670e34-b6d8-4dec-a375-684b206ff91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS Tutorial'])[1]/following::a[2]</value>
      <webElementGuid>020ddff5-3d05-490b-a5b3-934100e36ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS Where To'])[1]/preceding::a[1]</value>
      <webElementGuid>6d277a6a-7173-48b5-9975-5a4dc148b69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS Output'])[1]/preceding::a[2]</value>
      <webElementGuid>565589a5-821d-4765-a9fc-914084304970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JS Introduction']/parent::*</value>
      <webElementGuid>30655d69-6d20-466d-82ed-d144d62e95eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'js_intro.asp')]</value>
      <webElementGuid>fda52c99-d712-4ef1-b6f8-fb8929f2eadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a[2]</value>
      <webElementGuid>dbb37966-4746-4578-9dd6-a023a6f4e6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'js_intro.asp' and (text() = 'JS Introduction' or . = 'JS Introduction')]</value>
      <webElementGuid>ef74237b-8f9b-4718-a60a-33560cd504fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
