<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log In_shopee-searchbar-input__input</name>
   <tag></tag>
   <elementGuidId>7bc134ae-aaac-4f44-8282-c73d42e9766e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.shopee-searchbar-input__input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a312c32-f847-41a5-92fd-322d0c32a6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>terrypalmerid Diskon s/d 60%</value>
      <webElementGuid>2f8550ff-6299-48af-8b37-3f780f76a613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shopee-searchbar-input__input</value>
      <webElementGuid>a99c5119-99a6-4f59-bdb3-bc35931b3e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>276ebc5c-61fa-45a4-b2ae-eaf018bac258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>terrypalmerid Diskon s/d 60%</value>
      <webElementGuid>64bb5a14-f3db-44e5-97d6-5e37fe59b3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>74420324-2958-4a17-befc-12418890f5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>5a83117f-fe3d-40af-8055-a9a40158e3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>shopee-searchbar-listbox</value>
      <webElementGuid>9399ca23-a1a6-4b07-a143-f3cb3aa634af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;shopee-top shopee-top--sticky&quot;]/div[@class=&quot;container-wrapper header-with-search-wrapper&quot;]/div[@class=&quot;container header-with-search&quot;]/div[@class=&quot;header-with-search__search-section&quot;]/div[@class=&quot;shopee-searchbar shopee-searchbar--focus&quot;]/div[@class=&quot;shopee-searchbar__main&quot;]/form[@class=&quot;shopee-searchbar-input&quot;]/input[@class=&quot;shopee-searchbar-input__input&quot;]</value>
      <webElementGuid>f8217e25-faae-49da-8ee3-6bf123ce2e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>63f24ae6-21c9-4957-91bc-7e4584a92080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div[2]/div/div/div/div/form/input</value>
      <webElementGuid>238ae7c5-87f8-400c-945d-2990c13e0ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2280ce70-456b-4944-9695-9d2bceba5737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'terrypalmerid Diskon s/d 60%']</value>
      <webElementGuid>d196f1cc-2123-4c3c-9f22-7929bb88f996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
