<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Terlaris</name>
   <tag></tag>
   <elementGuidId>0d48d997-8798-4c8a-802f-a62e930c0a0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[3]/div/div/div[2]/div[2]/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c01d2cc3-f97e-4ea3-bb32-0e2e8eb54a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shopee-sort-by-options__option</value>
      <webElementGuid>ad2f2b03-cf4e-4f98-b93a-488b4b0aadc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terlaris</value>
      <webElementGuid>27bf0fed-6532-4619-8f8b-69970a25c15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;dYFPlI&quot;]/div[@class=&quot;_9dX3ZL&quot;]/div[@class=&quot;container +eN62l&quot;]/div[@class=&quot;ZgwlcK&quot;]/div[@class=&quot;shopee-search-item-result&quot;]/div[@class=&quot;shopee-sort-bar&quot;]/div[@class=&quot;shopee-sort-by-options&quot;]/div[@class=&quot;shopee-sort-by-options__option&quot;]</value>
      <webElementGuid>72f45d1d-8bf8-4665-9c54-6b15c7885c18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[3]/div/div/div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>7f6c5226-be8d-4fd9-88b4-b16e96e41342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terbaru'])[1]/following::div[1]</value>
      <webElementGuid>665cea82-24fa-42a1-8569-6045f95d68b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terkait'])[1]/following::div[2]</value>
      <webElementGuid>736e79d7-b1ea-4d30-aaec-f73a1485bdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[1]/preceding::div[1]</value>
      <webElementGuid>cc5d792a-6d6b-44a6-811a-7f7df9a7b71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terlaris']/parent::*</value>
      <webElementGuid>217f2bc0-aa81-48f9-8975-4bb09386d6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>e9ee5f8d-1f58-4a9c-8625-9e4264269b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Terlaris' or . = 'Terlaris')]</value>
      <webElementGuid>50dd5758-1843-4b39-b0dc-05a66adee538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
